### ISSUE TITLE
Issue with JEI and Farmers Croptopia addon

### ISSUE THREAD

**Issue by SalviniaChina** [ACCBDD/farmers-croptopia#1]
When JEI and Farmers Croptopia are added together there is this issue that there is a java.lang.pointer exception.
[message-1.txt](https://github.com/user-attachments/files/17706932/message-1.txt)

**Comment by ACCBDD** [comment]
thanks for reporting this! unfortunately, I can't reproduce this error. can you try to reproduce it on a fresh install?
