### ISSUE TITLE
Farmer's Croptopia Removes Fried Egg Recipe

### ISSUE THREAD

**Issue by Frankiscophil** [ACCBDD/farmers-croptopia#2]
**Describe the bug**
Farmer's Croptopia causes the Fried Egg from Farmer's Delight to become unavailable.

**To Reproduce**
1. Install Farmer's Croptopia 1.1.0 and Farmer's Delight 1.2.5, and Croptopia 4.0.1 in a minecraft 1.21.1 neoforge instance.
2. Install JEI as well to observe the recipe invalidity.
3. Launch the instance and enter a save/world. 
4. Look at any Farmer's Delight recipe that requires eggs in JEI.

**Expected behavior**
I should be able to craft the Fried Egg item and use it to make higher tier food.

**Screenshots**
![2024-11-28_03 06 49](https://github.com/user-attachments/assets/4cae4a1d-aa24-4763-9fbe-4d8431c449e6)
![2024-11-28_03 06 52](https://github.com/user-attachments/assets/f8fbda52-cdcc-42b2-9bd1-2592a74d1e70)

**Comment by ACCBDD** [comment]
fixed in 1.21.1-1.1.1
